// lib/industryDefaults.ts
// Default study config values per industry

import type { StudyConfig } from './types'

export type Industry =
  | 'automotive_repair'
  | 'casual_dining'
  | 'education'
  | 'fast_food'
  | 'financial_services'
  | 'fine_dining'
  | 'hr_employee'
  | 'healthcare'
  | 'higher_education'
  | 'hospitality'
  | 'media_entertainment'
  | 'nonprofits'
  | 'performing_arts'
  | 'political'
  | 'retail_ecommerce'
  | 'saas_software'
  | 'sports'
  | 'travel_tourism'
  | 'other'

export const INDUSTRY_LABELS: Record<Industry, string> = {
  automotive_repair:   'Automotive Repair',
  casual_dining:       'Casual Dining',
  education:           'Education',
  fast_food:           'Fast Food',
  financial_services:  'Financial Services',
  fine_dining:         'Fine Dining',
  hr_employee:         'HR / Employee Experience',
  healthcare:          'Healthcare',
  higher_education:    'Higher Education',
  hospitality:         'Hospitality / Hotels',
  media_entertainment: 'Media / Entertainment',
  nonprofits:          'Non-Profits',
  performing_arts:     'Performing Arts / Venues',
  political:           'Political Opinion Survey',
  retail_ecommerce:    'Retail / E-commerce',
  saas_software:       'SaaS / Software',
  sports:              'Sports',
  travel_tourism:      'Travel / Tourism',
  other:               'Other / Custom',
}

type Defaults = Pick<StudyConfig,
  'greeting' | 'ratingPrompt' |
  'promoterQ1' | 'passiveQ1' | 'detractorQ1' |
  'q3' | 'q4' | 'clarifiers' | 'psychographicBank'
>

export const INDUSTRY_DEFAULTS: Record<Exclude<Industry, 'other'>, Defaults> = {

  automotive_repair: {
    greeting: "Hi -- thanks for choosing us for your vehicle service. We'd love to hear about your experience today.",
    ratingPrompt: "How would you rate your overall service experience today?",
    promoterQ1: "That's great to hear! What stood out most about the service you received?",
    passiveQ1: "Thank you for the feedback. What could we have done to make your experience even better?",
    detractorQ1: "I'm sorry to hear that. What fell short of your expectations today?",
    q3: "Was there anything about the communication, wait time, or quality of work you'd like to highlight?",
    q4: "Is there anything else you'd like us to know about your visit?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      wait: "How long did you wait, and did we keep you informed during that time?",
      price: "Was the pricing unclear upfront, or did the final cost differ from your expectation?",
      quality: "Which aspect of the work are you referring to?",
    },
    psychographicBank: [
      { key: 'ar_vehicle_type', q: "What type of vehicle do you drive?", exportLabel: "Vehicle Type",
        opts: ["Sedan or coupe", "SUV or crossover", "Truck or van", "Luxury vehicle", "Electric or hybrid", "Commercial vehicle"] },
      { key: 'ar_service_type', q: "What brought you in today?", exportLabel: "Service Type",
        opts: ["Routine maintenance", "Brake service", "Engine or mechanical repair", "Electrical issue", "Body or collision work", "Inspection or diagnostic"] },
      { key: 'ar_customer_tenure', q: "How long have you been a customer here?", exportLabel: "Customer Tenure",
        opts: ["First time", "Less than a year", "1-3 years", "3-5 years", "More than 5 years"] },
      { key: 'ar_find_us', q: "How did you find us?", exportLabel: "Discovery Channel",
        opts: ["Google search", "Recommendation from friend or family", "Online review site", "Returning customer", "Drove past or saw signage"] },
      { key: 'ar_service_frequency', q: "How often do you have your vehicle serviced?", exportLabel: "Service Frequency",
        opts: ["More than once a year", "Once a year", "Every 2-3 years", "Only when something goes wrong"] },
    ],
  },

  casual_dining: {
    greeting: "Hi -- thanks for dining with us today! We'd love to hear how your experience was.",
    ratingPrompt: "How would you rate your overall dining experience today?",
    promoterQ1: "Fantastic! What made your meal or visit stand out?",
    passiveQ1: "Thanks for dining with us. What could we have done to make your experience even better?",
    detractorQ1: "I'm sorry to hear that. What let you down about your experience today?",
    q3: "Were there any specific aspects -- the food, service, atmosphere, or wait time -- you'd like to highlight?",
    q4: "Is there anything else you'd like us to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      food: "Which dish or item are you referring to?",
      service: "Was this about speed of service, attentiveness, or something else?",
      wait: "How long did you wait, and at what point -- being seated, ordering, or receiving your food?",
    },
    psychographicBank: [
      { key: 'cd_visit_occasion', q: "What brought you in today?", exportLabel: "Visit Occasion",
        opts: ["Casual meal out", "Family dinner", "Lunch break", "Special occasion", "First time trying us"] },
      { key: 'cd_party_size', q: "How large was your group today?", exportLabel: "Party Size",
        opts: ["Just me", "2 people", "3-4 people", "5 or more"] },
      { key: 'cd_visit_frequency', q: "How often do you dine with us?", exportLabel: "Visit Frequency",
        opts: ["First time", "Occasionally", "A few times a month", "Weekly or more"] },
      { key: 'cd_meal_period', q: "Which meal period was your visit?", exportLabel: "Meal Period",
        opts: ["Breakfast", "Brunch", "Lunch", "Dinner", "Late night"] },
      { key: 'cd_discovery', q: "How did you hear about us?", exportLabel: "Discovery Channel",
        opts: ["Word of mouth", "Social media", "Google search", "Walked past", "Returning regular"] },
    ],
  },

  education: {
    greeting: "Hi -- thank you for taking a moment to share your feedback. Your input helps us make our school community better for everyone.",
    ratingPrompt: "How would you rate your overall experience with our school this year?",
    promoterQ1: "That's wonderful to hear! What has been most positive about your experience?",
    passiveQ1: "Thank you for sharing. What could we do to make your experience even better?",
    detractorQ1: "I'm sorry to hear that. What area has caused the most concern for you?",
    q3: "Are there specific programs, staff, or processes you'd like to highlight -- positively or as areas to improve?",
    q4: "Is there anything else you'd like us to know about your experience?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      teacher: "Which subject or classroom are you referring to?",
      communication: "What type of communication are you referring to -- updates, reports, or something else?",
      safety: "Could you share more about the safety concern you have in mind?",
    },
    psychographicBank: [
      { key: 'ed_role', q: "What is your relationship to our school?", exportLabel: "Role",
        opts: ["Student", "Parent or guardian", "Teacher or staff", "Administrator", "Community member"] },
      { key: 'ed_grade_level', q: "What grade level are you associated with?", exportLabel: "Grade Level",
        opts: ["Elementary (K-5)", "Middle school (6-8)", "High school (9-12)", "Multiple grades"] },
      { key: 'ed_involvement', q: "How involved are you in school activities?", exportLabel: "Involvement Level",
        opts: ["Very involved", "Somewhat involved", "Occasionally involved", "Not very involved"] },
      { key: 'ed_primary_concern', q: "What area matters most to you right now?", exportLabel: "Primary Concern",
        opts: ["Academic performance", "Student wellbeing", "Safety and security", "Communication", "Extracurricular programs"] },
      { key: 'ed_comms_pref', q: "How do you prefer to receive school updates?", exportLabel: "Comms Preference",
        opts: ["Email", "School app or portal", "Text message", "Social media", "In-person meetings"] },
    ],
  },

  fast_food: {
    greeting: "Hi -- thanks for visiting us today! We'd love to hear about your experience. It only takes a minute.",
    ratingPrompt: "How would you rate your overall experience today?",
    promoterQ1: "Great to hear! What made your visit stand out?",
    passiveQ1: "Thank you for stopping by. What could we have done better today?",
    detractorQ1: "I'm sorry your experience didn't meet expectations. What was the main issue?",
    q3: "Was there anything specific about your order, the wait, or the service that you'd like to mention?",
    q4: "Is there anything else you'd like us to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      wait: "How long did you wait, and where did the delay happen?",
      order: "Was this an issue with accuracy, temperature, or something else?",
      staff: "Was this at the counter, drive-through, or another point of contact?",
    },
    psychographicBank: [
      { key: 'ff_order_method', q: "How did you place your order today?", exportLabel: "Order Method",
        opts: ["Dine-in counter", "Drive-through", "Mobile app pickup", "Third-party delivery", "Curbside pickup"] },
      { key: 'ff_visit_time', q: "What time of day was your visit?", exportLabel: "Visit Time",
        opts: ["Breakfast (before 11am)", "Lunch (11am-2pm)", "Afternoon snack", "Dinner (after 5pm)", "Late night"] },
      { key: 'ff_visit_frequency', q: "How often do you visit us?", exportLabel: "Visit Frequency",
        opts: ["Daily or almost daily", "Several times a week", "Once a week", "A few times a month", "Rarely"] },
      { key: 'ff_reason', q: "Why did you choose us today?", exportLabel: "Reason for Choosing",
        opts: ["Convenience or location", "Speed", "Price", "Favourite menu item", "Habit"] },
      { key: 'ff_party_size', q: "How many people did you order for?", exportLabel: "Party Size",
        opts: ["Just me", "2 people", "3-4 people", "5 or more"] },
    ],
  },

  financial_services: {
    greeting: "Hi -- we value your feedback about your experience with us. Your input helps us serve you better.",
    ratingPrompt: "How would you rate your overall experience with us today?",
    promoterQ1: "That's great to hear! What has made your experience with us particularly positive?",
    passiveQ1: "Thank you for your feedback. What could we do to serve you even better?",
    detractorQ1: "I'm sorry to hear that. What aspect of your experience fell short?",
    q3: "Were there any specific interactions, processes, or products you'd like to highlight?",
    q4: "Is there anything else you'd like us to know about your experience?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      fees: "Which fees or charges are you referring to?",
      process: "Which step of the process caused frustration?",
      staff: "Was this with a specific team or department?",
    },
    psychographicBank: [
      { key: 'fs_service_type', q: "What type of service are you primarily giving feedback about?", exportLabel: "Service Type",
        opts: ["Personal banking", "Business banking", "Mortgage or home loan", "Investments or retirement", "Insurance", "Credit card"] },
      { key: 'fs_customer_tenure', q: "How long have you been our customer?", exportLabel: "Customer Tenure",
        opts: ["Less than a year", "1-3 years", "3-7 years", "More than 7 years"] },
      { key: 'fs_primary_channel', q: "How do you primarily manage your account?", exportLabel: "Primary Channel",
        opts: ["Mobile app", "Online banking", "Branch in person", "Phone", "Mix of all"] },
      { key: 'fs_primary_concern', q: "What is your top financial concern right now?", exportLabel: "Financial Concern",
        opts: ["Building savings", "Managing debt", "Retirement planning", "Buying a home", "Growing investments", "Business finances"] },
      { key: 'fs_trust_driver', q: "What matters most when choosing a financial institution?", exportLabel: "Trust Driver",
        opts: ["Security and safety", "Low fees", "Interest rates", "Customer service", "Convenience", "Digital tools"] },
    ],
  },

  fine_dining: {
    greeting: "Good evening -- thank you for joining us tonight. Your feedback helps us create exceptional experiences for every guest.",
    ratingPrompt: "How would you rate your overall dining experience tonight?",
    promoterQ1: "We're delighted to hear that! What made your evening most memorable?",
    passiveQ1: "Thank you for dining with us. What could we have done to elevate your experience further?",
    detractorQ1: "We sincerely apologize that tonight did not meet your expectations. What fell short?",
    q3: "Were there any specific moments -- the food, service, wine, or atmosphere -- you'd like to share thoughts on?",
    q4: "Is there anything else you'd like us to know?",
    clarifiers: {
      default: "Could you share a little more about that?",
      food: "Which course or dish are you referring to?",
      service: "Was this about pacing, attentiveness, or knowledge of the menu and wine list?",
      atmosphere: "Was this about the noise level, lighting, temperature, or something else?",
    },
    psychographicBank: [
      { key: 'fd_occasion', q: "What is the occasion for your visit tonight?", exportLabel: "Visit Occasion",
        opts: ["Anniversary or birthday", "Date night", "Business dinner", "Celebration", "Treating yourself", "First time visiting"] },
      { key: 'fd_party_size', q: "How large was your dining party?", exportLabel: "Party Size",
        opts: ["2 people", "3-4 people", "5-6 people", "7 or more"] },
      { key: 'fd_discovery', q: "How did you hear about us?", exportLabel: "Discovery Channel",
        opts: ["Word of mouth", "Online reviews", "Food publication or press", "Social media", "Returning guest"] },
      { key: 'fd_dining_frequency', q: "How often do you dine at fine dining restaurants?", exportLabel: "Fine Dining Frequency",
        opts: ["Rarely (special occasions only)", "A few times a year", "Monthly", "Regularly"] },
      { key: 'fd_importance', q: "What matters most in a fine dining experience?", exportLabel: "Key Priority",
        opts: ["Quality and creativity of the food", "Service and attentiveness", "Wine and beverage program", "Atmosphere and ambiance", "Exclusivity and prestige"] },
    ],
  },

  hr_employee: {
    greeting: "Hi -- thank you for taking a few minutes to share your experience as a member of our team. Your feedback is completely confidential.",
    ratingPrompt: "How would you rate your overall employee experience right now?",
    promoterQ1: "That's great to hear! What is making your experience most positive?",
    passiveQ1: "Thank you for sharing. What would make the biggest difference to your experience at work?",
    detractorQ1: "I'm sorry to hear that. What is having the biggest negative impact on your experience?",
    q3: "Are there any specific aspects of your day-to-day work, your team, or the broader organisation you'd like to highlight?",
    q4: "Is there anything else you'd like leadership to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      manager: "Is this about your direct manager, skip-level management, or leadership more broadly?",
      process: "Which process or system is causing the most friction?",
      culture: "Could you give me a specific example of what you're experiencing?",
    },
    psychographicBank: [
      { key: 'hr_department', q: "Which department are you in?", exportLabel: "Department",
        opts: ["Operations", "Sales or Marketing", "Technology or IT", "Finance", "HR or People", "Customer Success", "Executive or Leadership", "Other"] },
      { key: 'hr_tenure', q: "How long have you been with the company?", exportLabel: "Tenure",
        opts: ["Less than a year", "1-2 years", "3-5 years", "6-10 years", "More than 10 years"] },
      { key: 'hr_role_level', q: "How would you describe your role?", exportLabel: "Role Level",
        opts: ["Individual contributor", "Team lead or supervisor", "Manager", "Senior manager or director", "VP or above"] },
      { key: 'hr_work_arrangement', q: "What is your primary work arrangement?", exportLabel: "Work Arrangement",
        opts: ["Fully remote", "Hybrid (some in-office)", "Fully in-office"] },
      { key: 'hr_feedback_area', q: "Which area would you most like to see improved?", exportLabel: "Improvement Area",
        opts: ["Compensation and benefits", "Work-life balance", "Career development", "Management and leadership", "Culture and belonging", "Tools and processes"] },
    ],
  },

  healthcare: {
    greeting: "Hi -- I'm here to gather your feedback about your recent care experience. It'll only take a few minutes, and your input genuinely helps us improve.",
    ratingPrompt: "How would you rate your overall care experience today?",
    promoterQ1: "That's wonderful to hear! What stood out most about the care you received?",
    passiveQ1: "Thank you for sharing that. What could we have done to make your experience even better?",
    detractorQ1: "I'm sorry to hear that. Which aspect of your care experience fell short of your expectations?",
    q3: "Were there any specific moments -- with staff, the facility, or the process -- that you'd like to highlight?",
    q4: "Is there anything else about your visit today you'd like us to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      wait: "How long did you have to wait, and how did that affect your experience?",
      staff: "Which member of staff are you referring to, and what happened?",
      communication: "What information do you feel was missing or unclear?",
    },
    psychographicBank: [
      { key: 'hc_patient_type', q: "Which best describes your visit today?", exportLabel: "Patient Type",
        opts: ["New patient", "Returning patient", "Emergency or urgent care", "Follow-up appointment", "Procedure or surgery"] },
      { key: 'hc_visit_frequency', q: "How often do you visit our facility?", exportLabel: "Visit Frequency",
        opts: ["First time", "A few times a year", "Monthly", "Weekly or more", "As needed"] },
      { key: 'hc_primary_concern', q: "What was the primary reason for your visit?", exportLabel: "Primary Concern",
        opts: ["Routine check-up", "Illness or injury", "Chronic condition management", "Mental health", "Specialist referral"] },
      { key: 'hc_insurance_type', q: "How is your care typically covered?", exportLabel: "Insurance Type",
        opts: ["Private insurance", "Medicare or Medicaid", "Self-pay", "Workers compensation", "Prefer not to say"] },
      { key: 'hc_age_range', q: "Which age group do you fall into?", exportLabel: "Age Range",
        opts: ["18-34", "35-49", "50-64", "65 or over", "Prefer not to say"] },
    ],
  },

  higher_education: {
    greeting: "Hi -- thank you for sharing your experience with us. Your feedback helps us continually improve the quality of our academic community.",
    ratingPrompt: "How would you rate your overall experience at our institution?",
    promoterQ1: "That's great to hear! What has been the highlight of your experience?",
    passiveQ1: "Thank you for your feedback. What would make the biggest difference to your experience?",
    detractorQ1: "I'm sorry to hear that. What has had the greatest negative impact on your experience?",
    q3: "Are there specific academic programs, support services, or facilities you'd like to comment on?",
    q4: "Is there anything else you'd like us to know about your experience?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      professor: "Which department or type of course are you referring to?",
      services: "Which student service or administrative office are you referring to?",
      campus: "Which area of campus or which facility are you referring to?",
    },
    psychographicBank: [
      { key: 'he_role', q: "What is your primary role?", exportLabel: "Role",
        opts: ["Undergraduate student", "Graduate or doctoral student", "Faculty", "Staff or administrator", "Alumni", "Parent or guardian"] },
      { key: 'he_year', q: "If you are a student, what year are you?", exportLabel: "Year or Level",
        opts: ["First year", "Sophomore", "Junior", "Senior", "Graduate", "Not currently enrolled"] },
      { key: 'he_enrollment_type', q: "What is your enrollment or engagement status?", exportLabel: "Enrollment Type",
        opts: ["Full-time on campus", "Part-time", "Online or distance", "Hybrid", "Not currently enrolled"] },
      { key: 'he_affiliation_length', q: "How long have you been affiliated with the institution?", exportLabel: "Affiliation Length",
        opts: ["Less than a year", "1-2 years", "3-4 years", "5 or more years", "Alumni (graduated)"] },
      { key: 'he_primary_concern', q: "What matters most to you right now?", exportLabel: "Primary Concern",
        opts: ["Academic quality and rigor", "Career preparation and placement", "Campus life and community", "Cost and financial aid", "Research opportunities", "Administrative services"] },
    ],
  },

  hospitality: {
    greeting: "Hi -- we'd love to hear about your stay with us. Your feedback genuinely helps us improve for every guest.",
    ratingPrompt: "How would you rate your overall stay experience?",
    promoterQ1: "Wonderful! What made your stay particularly memorable?",
    passiveQ1: "Thank you for staying with us. What could we have done to make your visit even more enjoyable?",
    detractorQ1: "I'm sorry your stay didn't meet your expectations. What was the main issue you experienced?",
    q3: "Were there any specific areas -- check-in, your room, dining, or service -- you'd particularly like to comment on?",
    q4: "Is there anything else you'd like us to know before you go?",
    clarifiers: {
      default: "Could you tell me a little more about that?",
      room: "What specifically about the room are you referring to?",
      staff: "Which part of our team are you referring to, and what happened?",
      cleanliness: "Which area or item are you referring to when it comes to cleanliness?",
    },
    psychographicBank: [
      { key: 'ho_travel_purpose', q: "What was the primary purpose of your stay?", exportLabel: "Travel Purpose",
        opts: ["Leisure or vacation", "Business", "Conference or event", "Special occasion", "Passing through"] },
      { key: 'ho_party_type', q: "Who did you travel with?", exportLabel: "Travel Party",
        opts: ["Alone", "Couple", "Family with children", "Group of friends", "Business colleagues"] },
      { key: 'ho_stay_frequency', q: "How often do you stay at properties like ours?", exportLabel: "Stay Frequency",
        opts: ["First time here", "Once a year", "A few times a year", "Monthly or more"] },
      { key: 'ho_booking_channel', q: "How did you book your stay?", exportLabel: "Booking Channel",
        opts: ["Direct hotel website", "Booking.com or Expedia", "Travel agent", "Corporate booking", "Loyalty programme"] },
      { key: 'ho_room_type', q: "What type of room did you stay in?", exportLabel: "Room Type",
        opts: ["Standard or queen", "King", "Suite", "Accessible room", "Other"] },
    ],
  },

  media_entertainment: {
    greeting: "Hi -- thank you for being part of our audience. We'd love to hear your thoughts on your experience with us.",
    ratingPrompt: "How would you rate your overall experience with our content or platform?",
    promoterQ1: "Love to hear that! What has been most compelling about our content for you?",
    passiveQ1: "Thank you for sharing. What would make our content or platform more valuable to you?",
    detractorQ1: "I'm sorry to hear that. What has been most disappointing about your experience?",
    q3: "Are there specific shows, articles, features, or content types you'd like to highlight or see more of?",
    q4: "Is there anything else about your experience with us you'd like to share?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      content: "Which type of content or specific show or article are you referring to?",
      platform: "Is this about the app, the website, or how content is delivered?",
      subscription: "Is this about the value you get relative to the cost?",
    },
    psychographicBank: [
      { key: 'me_content_type', q: "What type of content do you primarily consume with us?", exportLabel: "Content Type",
        opts: ["News and journalism", "Music and podcasts", "Streaming TV or film", "Live sports", "Gaming", "Social media content"] },
      { key: 'me_frequency', q: "How often do you engage with our content?", exportLabel: "Engagement Frequency",
        opts: ["Daily", "Several times a week", "Weekly", "A few times a month", "Occasionally"] },
      { key: 'me_primary_device', q: "What device do you mainly use?", exportLabel: "Primary Device",
        opts: ["Smartphone", "Smart TV", "Laptop or desktop", "Tablet", "Multiple devices equally"] },
      { key: 'me_subscription', q: "What is your subscription status?", exportLabel: "Subscription Status",
        opts: ["Paid subscriber", "Free tier user", "Trial user", "Lapsed subscriber considering return"] },
      { key: 'me_discovery', q: "How do you typically discover new content?", exportLabel: "Discovery Method",
        opts: ["Algorithm recommendations", "Social media", "Word of mouth", "Editorial picks", "Browsing myself"] },
    ],
  },

  nonprofits: {
    greeting: "Hi -- thank you so much for your involvement with our organisation. Your feedback helps us serve our mission more effectively.",
    ratingPrompt: "How would you rate your overall experience with our organisation?",
    promoterQ1: "That means a lot to us! What has made your experience most meaningful?",
    passiveQ1: "Thank you for your time. What would make your experience with us even more rewarding?",
    detractorQ1: "I'm sorry to hear that. What has been the biggest challenge in your experience with us?",
    q3: "Are there specific programs, communications, or interactions you'd like to highlight?",
    q4: "Is there anything else you'd like us to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      program: "Which specific program or initiative are you referring to?",
      communication: "Is this about how we communicate our impact, our needs, or something else?",
      volunteer: "Was this about the organisation, a specific event, or the team you worked with?",
    },
    psychographicBank: [
      { key: 'np_relationship', q: "How are you involved with our organisation?", exportLabel: "Relationship Type",
        opts: ["Financial donor", "Regular volunteer", "Program participant or beneficiary", "Board or committee member", "Partner organisation", "New supporter"] },
      { key: 'np_duration', q: "How long have you been connected to us?", exportLabel: "Involvement Duration",
        opts: ["Less than a year", "1-3 years", "3-5 years", "More than 5 years"] },
      { key: 'np_discovery', q: "How did you first learn about us?", exportLabel: "Discovery Channel",
        opts: ["Friend or family recommendation", "Social media", "Internet search", "Community event", "News coverage"] },
      { key: 'np_motivation', q: "What primarily motivates your involvement?", exportLabel: "Motivation",
        opts: ["Belief in the mission", "Personal connection to the cause", "Community impact", "Skills-based contribution", "Recognition", "Other"] },
      { key: 'np_engagement_pref', q: "How do you prefer to stay engaged?", exportLabel: "Engagement Preference",
        opts: ["Email updates", "Social media", "In-person events", "Volunteer opportunities", "Annual impact report"] },
    ],
  },

  performing_arts: {
    greeting: "Hi -- thank you for joining us today. We'd love to hear about your experience. Your feedback helps us create unforgettable performances for everyone.",
    ratingPrompt: "How would you rate your overall experience today?",
    promoterQ1: "Wonderful! What was the highlight of the experience for you?",
    passiveQ1: "Thank you for coming. What could we have done to make it even more memorable?",
    detractorQ1: "I'm sorry the experience didn't quite meet your expectations. What let you down?",
    q3: "Were there any specific aspects -- the performance, venue, staff, or logistics -- you'd like to comment on?",
    q4: "Is there anything else you'd like to share about today?",
    clarifiers: {
      default: "Could you tell me a little more about that?",
      venue: "Was this about the physical space, seating, facilities, or acoustics?",
      performance: "Which part of the performance are you referring to?",
      access: "Was this about ticketing, parking, entry, or navigating the venue?",
    },
    psychographicBank: [
      { key: 'pa_performance_type', q: "What type of performance brought you here today?", exportLabel: "Performance Type",
        opts: ["Orchestra or classical music", "Theater or drama", "Ballet or dance", "Opera", "Musical theater", "Comedy or spoken word", "Contemporary or experimental"] },
      { key: 'pa_ticket_acquisition', q: "How did you get your tickets?", exportLabel: "Ticket Acquisition",
        opts: ["Online in advance", "Box office on the day", "Season ticket or subscription", "Gift", "Complimentary or guest list"] },
      { key: 'pa_frequency', q: "How often do you attend live performances?", exportLabel: "Attendance Frequency",
        opts: ["This is my first time", "Once or twice a year", "A few times a year", "Monthly or more"] },
      { key: 'pa_distance', q: "How far did you travel to attend?", exportLabel: "Travel Distance",
        opts: ["Under 15 minutes", "15-30 minutes", "30-60 minutes", "Over an hour", "Travelled from out of town"] },
      { key: 'pa_group', q: "Who did you come with today?", exportLabel: "Group Composition",
        opts: ["Alone", "Partner or spouse", "Friends", "Family with children", "Adult family members"] },
    ],
  },

  political: {
    greeting: "Hi -- thank you for taking a moment to share your views. Your voice matters and we want to make sure it's heard.",
    ratingPrompt: "How would you rate your overall impression of what you've heard or seen from us recently?",
    promoterQ1: "That's great to hear! What has resonated most with you?",
    passiveQ1: "Thank you for your time. What could we be doing better to connect with you and your community?",
    detractorQ1: "I appreciate your honesty. What has fallen short of your expectations?",
    q3: "Are there specific issues or topics you feel aren't being adequately addressed?",
    q4: "Is there anything else you'd like our team to know?",
    clarifiers: {
      default: "Could you tell me a bit more about what you mean?",
      policy: "Which specific policy area are you referring to?",
      communication: "How would you prefer to receive information and updates?",
      event: "Was there a particular moment, statement, or interaction you're referring to?",
    },
    psychographicBank: [
      { key: 'po_voter_status', q: "Are you a registered voter in this area?", exportLabel: "Voter Status",
        opts: ["Yes, registered here", "Yes, registered elsewhere", "Not currently registered", "Prefer not to say"] },
      { key: 'po_engagement_level', q: "How engaged are you in local or national politics?", exportLabel: "Engagement Level",
        opts: ["Very engaged -- I follow closely", "Somewhat engaged", "Occasionally interested", "Not usually engaged"] },
      { key: 'po_top_issue', q: "Which issue matters most to you right now?", exportLabel: "Top Issue",
        opts: ["Economy and jobs", "Healthcare", "Education", "Public safety", "Climate and environment", "Immigration", "Other"] },
      { key: 'po_political_lean', q: "How would you describe your political leaning?", exportLabel: "Political Leaning",
        opts: ["Progressive or left", "Centre-left", "Centrist", "Centre-right", "Conservative or right", "Prefer not to say"] },
      { key: 'po_local_area', q: "Which area do you primarily identify with?", exportLabel: "Geographic Area",
        opts: ["Urban", "Suburban", "Rural", "Small town", "Prefer not to say"] },
    ],
  },

  retail_ecommerce: {
    greeting: "Hi -- thank you for shopping with us! We'd love to hear about your experience today.",
    ratingPrompt: "How would you rate your overall shopping experience?",
    promoterQ1: "So glad to hear that! What stood out most about your experience?",
    passiveQ1: "Thank you for sharing. What could we have done to make your shopping experience even better?",
    detractorQ1: "I'm sorry to hear that. What let you down about your experience today?",
    q3: "Was there anything about the product selection, checkout process, or service you'd like to highlight?",
    q4: "Is there anything else you'd like us to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      product: "Which item or category are you referring to?",
      shipping: "Was this about delivery speed, packaging, or tracking?",
      return: "Was the return or exchange process unclear, inconvenient, or something else?",
    },
    psychographicBank: [
      { key: 're_shopping_channel', q: "How do you primarily shop with us?", exportLabel: "Shopping Channel",
        opts: ["In-store only", "Online only", "Both in-store and online", "Mobile app"] },
      { key: 're_purchase_frequency', q: "How often do you purchase from us?", exportLabel: "Purchase Frequency",
        opts: ["First time", "Rarely", "A few times a year", "Monthly", "Weekly or more"] },
      { key: 're_product_category', q: "What do you most often purchase?", exportLabel: "Product Category",
        opts: ["Clothing and apparel", "Electronics", "Home and garden", "Health and beauty", "Food and grocery", "Other"] },
      { key: 're_discovery', q: "How did you find us or this product today?", exportLabel: "Discovery Channel",
        opts: ["Search engine", "Social media", "Friend recommendation", "Email promotion", "Already a regular customer"] },
      { key: 're_loyalty', q: "Are you a member of our rewards or loyalty program?", exportLabel: "Loyalty Status",
        opts: ["Yes, active member", "Yes but I rarely use it", "No but I am interested", "No, not interested"] },
    ],
  },

  saas_software: {
    greeting: "Hi -- thanks for taking a moment to share your experience with our product. Your feedback directly shapes what we build next.",
    ratingPrompt: "How would you rate your overall experience with our product?",
    promoterQ1: "That's great to hear! What has made our product most valuable to you?",
    passiveQ1: "Thank you for your feedback. What would have the biggest positive impact on your experience?",
    detractorQ1: "I'm sorry to hear that. What has been the biggest pain point or frustration?",
    q3: "Are there specific features, workflows, or parts of the product you'd like to highlight -- positively or as areas to improve?",
    q4: "Is there anything else you'd like our product team to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      feature: "Which specific feature or part of the product are you referring to?",
      performance: "Is this about speed, reliability, or something not working as expected?",
      onboarding: "Which part of the setup or getting-started process caused the difficulty?",
    },
    psychographicBank: [
      { key: 'ss_role', q: "What best describes your role?", exportLabel: "Role",
        opts: ["Individual end user", "Team lead or manager", "IT administrator", "Business owner", "Developer or engineer", "Executive"] },
      { key: 'ss_company_size', q: "How large is your organisation?", exportLabel: "Company Size",
        opts: ["Just me (freelancer)", "2-10 people", "11-50 people", "51-250 people", "251-1000 people", "Over 1000 people"] },
      { key: 'ss_usage_tenure', q: "How long have you been using our product?", exportLabel: "Usage Tenure",
        opts: ["Less than a month", "1-6 months", "6-12 months", "1-2 years", "More than 2 years"] },
      { key: 'ss_primary_use_case', q: "What is your primary use case?", exportLabel: "Primary Use Case",
        opts: ["Project management", "Communication or collaboration", "Analytics or reporting", "Customer management", "Development or DevOps", "Finance or operations"] },
      { key: 'ss_technical_comfort', q: "How would you rate your technical proficiency?", exportLabel: "Technical Proficiency",
        opts: ["Non-technical -- I need things simple", "Moderately technical", "Technical -- comfortable with advanced features"] },
    ],
  },

  sports: {
    greeting: "Hi -- thank you for your support! We'd love to hear about your experience as a fan. This only takes a couple of minutes.",
    ratingPrompt: "How would you rate your overall experience as a fan right now?",
    promoterQ1: "Love to hear that! What has made you most proud or excited about your experience?",
    passiveQ1: "Thanks for being with us. What would make your experience as a fan even better?",
    detractorQ1: "I'm sorry to hear that. What has been most frustrating or disappointing?",
    q3: "Is there anything specific about the team, events, communication, or fan experience you'd like to highlight?",
    q4: "Is there anything else you'd like us to know?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      gameday: "Is this about the in-venue experience, ticketing, or something else on game day?",
      team: "Is this about on-field performance, management decisions, or something else?",
      communication: "Is this about social media, email, the app, or another communication channel?",
    },
    psychographicBank: [
      { key: 'sp_fan_level', q: "How would you describe your level of fandom?", exportLabel: "Fan Level",
        opts: ["Casual fan", "Regular follower", "Dedicated fan", "Die-hard or superfan"] },
      { key: 'sp_follow_method', q: "How do you primarily follow the team or sport?", exportLabel: "Follow Method",
        opts: ["Attending games in person", "Watching on TV or cable", "Streaming online", "Following on social media", "Reading news or podcasts"] },
      { key: 'sp_season_ticket', q: "Are you a season ticket holder or member?", exportLabel: "Season Ticket Status",
        opts: ["Yes, current season ticket holder", "Yes, I have a membership", "Previously was, not currently", "No but considering it", "No"] },
      { key: 'sp_tenure', q: "How long have you been a fan?", exportLabel: "Fan Tenure",
        opts: ["Less than a year", "1-3 years", "3-10 years", "More than 10 years", "My whole life"] },
      { key: 'sp_game_attendance', q: "How often do you attend games or events in person?", exportLabel: "Game Attendance",
        opts: ["Every game or most games", "Several times a season", "Once or twice a season", "Rarely or never"] },
    ],
  },

  travel_tourism: {
    greeting: "Hi -- we'd love to hear about your recent travel experience with us. Your feedback helps us make every journey better.",
    ratingPrompt: "How would you rate your overall travel experience with us?",
    promoterQ1: "Great to hear! What stood out most about your journey?",
    passiveQ1: "Thank you for travelling with us. What could we have done to improve your experience?",
    detractorQ1: "I'm sorry the journey didn't meet your expectations. What was the main issue?",
    q3: "Were there any specific touchpoints -- booking, check-in, the journey itself, or arrival -- you'd like to comment on?",
    q4: "Is there anything else about your travel experience you'd like to share?",
    clarifiers: {
      default: "Could you tell me a bit more about that?",
      delay: "How long was the delay and how were you informed about it?",
      staff: "At which stage of your journey did this happen?",
      booking: "Was this a problem with the booking process itself, or something that came up later?",
    },
    psychographicBank: [
      { key: 'tt_trip_purpose', q: "What was the purpose of your trip?", exportLabel: "Trip Purpose",
        opts: ["Leisure or holiday", "Business travel", "Visiting family or friends", "Honeymoon or special occasion", "Group or packaged tour"] },
      { key: 'tt_travel_frequency', q: "How often do you travel?", exportLabel: "Travel Frequency",
        opts: ["Rarely (once a year or less)", "A few times a year", "Monthly", "Weekly or more"] },
      { key: 'tt_booking_method', q: "How did you book your travel?", exportLabel: "Booking Method",
        opts: ["Direct with the provider", "OTA (Expedia, Kayak etc.)", "Travel agent", "Corporate travel desk", "Loyalty app"] },
      { key: 'tt_party_type', q: "Who did you travel with?", exportLabel: "Travel Party",
        opts: ["Solo", "Couple", "Family with children", "Group of friends", "Business colleagues"] },
      { key: 'tt_destination_type', q: "Which best describes your destination?", exportLabel: "Destination Type",
        opts: ["Domestic city break", "Domestic longer trip", "International short-haul", "International long-haul", "Cruise or expedition"] },
    ],
  },
}
