// lib/funFacts.ts
// The Data Story building screen's "Did you know?" pool (owner, 2026-09-02:
// lots of real fun facts, sciencefocus.com spirit, random rotation).
//
// House rules for this list:
//   - Every fact is WELL-DOCUMENTED, not merely widely repeated — the famous
//     myths (goldfish memory, Great Wall from space, lobster immortality,
//     flowing cathedral glass) are deliberately absent.
//   - Every fact is written in OUR OWN words. Facts are free; a publisher's
//     exact wording and curated compilation are not, so nothing here is
//     quoted or transcribed from any single source's list.
//   - One crisp sentence each; estimates say "about"/"estimated".

export const FUN_FACTS: string[] = [
  // ── Space ───────────────────────────────────────────────────────────
  'A day on Venus lasts longer than its year — the planet spins slower than it orbits the Sun.',
  'Venus, not Mercury, is the hottest planet in the solar system, despite being farther from the Sun.',
  'The Moon is drifting away from Earth at about 3.8 centimeters per year.',
  'A single teaspoon of neutron-star material would weigh billions of tons.',
  'Some neutron stars spin hundreds of times every second.',
  'The Sun holds about 99.8% of all the mass in the solar system.',
  'Roughly a million Earths would fit inside the Sun.',
  'Energy made in the Sun’s core takes on the order of 100,000 years to reach its surface — then just over 8 minutes to reach Earth.',
  'Jupiter’s Great Red Spot is a storm bigger than Earth that has raged for centuries.',
  'Saturn’s average density is lower than water’s.',
  'Olympus Mons on Mars stands about two and a half times the height of Everest.',
  'Sunsets on Mars are blue.',
  'It rains methane on Saturn’s moon Titan.',
  'A year on Neptune lasts about 165 Earth years.',
  'Footprints left on the Moon could last millions of years — there is no wind or rain to erase them.',
  'The International Space Station circles the Earth about once every 90 minutes.',
  'Astronauts return from long missions up to about 5 centimeters taller — their spines stretch without gravity.',
  'Mercury and Venus are the only planets in our solar system without moons.',
  'Two pieces of the same bare metal that touch in the vacuum of space can weld themselves together.',
  'Halley’s Comet returns about every 76 years — next expected in 2061.',
  'Sound cannot travel through the vacuum of space.',
  'Astronomers estimate the observable universe contains about two trillion galaxies.',
  'There are more stars in the observable universe than grains of sand on all of Earth’s beaches.',
  'Trillions of neutrinos from the Sun pass harmlessly through your body every second.',
  'GPS only works because its satellites correct for Einstein’s relativity — without it, positions would drift kilometers per day.',
  'Astronomers found a cloud around a distant quasar holding about 140 trillion times the water in Earth’s oceans.',
  'Helium was discovered in the Sun’s light before anyone found it on Earth.',
  // ── Animals ─────────────────────────────────────────────────────────
  'An octopus has three hearts and blue blood.',
  'Most of an octopus’s neurons are in its arms, not its head.',
  'Sharks were swimming the oceans tens of millions of years before the first trees grew.',
  'Wombats are the only animals known to produce cube-shaped droppings.',
  'Tardigrades — microscopic “water bears” — have survived direct exposure to the vacuum of space.',
  'A sloth can hold its breath longer than a dolphin can.',
  'A Venus flytrap counts: it snaps shut only after two touches, to avoid false alarms.',
  'The blue whale is the largest animal known to have ever lived — bigger than any dinosaur.',
  'A blue whale’s heart is about the size of a bumper car and can weigh over 400 pounds.',
  'Hummingbirds are the only birds that can fly backwards.',
  'An ostrich’s eye is bigger than its brain.',
  'Butterflies taste with their feet.',
  'Axolotls can regrow limbs, spinal cord, and even parts of their heart and brain.',
  'One jellyfish species can revert to its juvenile form after adulthood — making it biologically able to restart its life cycle.',
  'Crows recognize individual human faces — and remember the ones that wronged them.',
  'Elephants are the only land mammals that cannot jump.',
  'A group of flamingos is called a flamboyance.',
  'Flamingos are born gray — their pink comes from their food.',
  'Sea otters sometimes hold hands while sleeping so they don’t drift apart.',
  'Cows form close friendships and show stress when separated from their preferred companions.',
  'Honeybees can learn to recognize human faces.',
  'Some desert snails can sleep for years waiting for rain.',
  'Polar bears have black skin under fur that isn’t actually white — each hair is transparent.',
  'Giraffes have the same number of neck vertebrae as you: seven.',
  'North American wood frogs survive winter by freezing nearly solid, then thawing out alive.',
  'Dolphins call each other by name — each develops its own signature whistle.',
  'Among seahorses, it’s the male that gives birth.',
  'Koala fingerprints are so similar to human ones they can confuse forensic analysis.',
  'A mantis shrimp strikes so fast the water around its club briefly boils.',
  'Bats are the only mammals capable of true powered flight.',
  'Owls can’t move their eyeballs — that’s why they rotate their heads up to about 270 degrees.',
  'Starfish manage without a brain and without blood.',
  'Camel humps store fat, not water.',
  'Goats have rectangular pupils, giving them panoramic vision.',
  'Gentoo penguins use pebbles in their courtship rituals.',
  'Cheetahs can’t roar — they meow and purr like house cats.',
  'Rats emit ultrasonic laughter when they are tickled.',
  'In a famous experiment, pigeons learned to tell Monet paintings from Picassos.',
  'Ants don’t have lungs — they breathe through tiny holes in their bodies.',
  'Dragonflies catch about 95% of the prey they target, making them among nature’s deadliest hunters.',
  'Jellyfish are about 95% water.',
  'Horseshoe crab blood is bright blue — and has been vital for testing the safety of vaccines and medical implants.',
  'Naked mole rats can survive around 18 minutes without oxygen and almost never get cancer.',
  'A hippo’s red “sweat” is a natural sunscreen and antibiotic.',
  'A garden snail has thousands of microscopic teeth on a ribbon-like tongue.',
  'Cats can’t taste sweetness.',
  'A dog’s nose print is unique, like a human fingerprint.',
  'Some sea cucumbers defend themselves by expelling their own internal organs — then regrow them.',
  // ── The human body ──────────────────────────────────────────────────
  'Your body is made of roughly 37 trillion cells.',
  'You carry about as many bacterial cells as human ones.',
  'Your stomach lining replaces itself every few days so you don’t digest yourself.',
  'Babies are born with around 300 bones; adults have 206 — many fuse along the way.',
  'The human eye can distinguish millions of colors.',
  'Stomach acid is strong enough to dissolve some metals.',
  'You are about a centimeter taller in the morning than at night — your spinal discs compress during the day.',
  'Fingernails grow noticeably faster than toenails.',
  'Your brain is about 2% of your body weight but uses around 20% of your energy.',
  'Your heart beats roughly 100,000 times a day.',
  'Humans are faintly bioluminescent — we glow, about a thousand times too dimly for our eyes to see.',
  'Goosebumps are a leftover reflex from ancestors whose raised fur made them look bigger and kept them warmer.',
  'The fastest signals in your nerves travel at over 100 meters per second.',
  'Your body contains roughly enough iron to forge a small nail.',
  'Tooth enamel is the hardest substance your body makes.',
  'Laid end to end, the DNA in your cells would stretch billions of kilometers.',
  'An adult human body is roughly 60% water.',
  'Humans are the only animals with true chins.',
  'The human nose can detect geosmin — the smell of rain on dry earth — at astonishingly tiny concentrations.',
  // ── Earth, physics & chemistry ──────────────────────────────────────
  'A bolt of lightning is roughly five times hotter than the surface of the Sun.',
  'Lightning strikes the Earth about a hundred times every second.',
  'When lightning strikes sand it can fuse it into natural glass tubes called fulgurites.',
  'Oxygen is the most abundant element in the Earth’s crust.',
  'Diamond and pencil lead are both pure carbon — just arranged differently.',
  'Water is one of very few substances whose solid form floats on its liquid.',
  'At absolute zero, −273.15°C, atoms nearly stop moving — and it can never quite be reached.',
  'Sound travels more than four times faster in water than in air.',
  'The Earth’s inner core is about as hot as the surface of the Sun.',
  'The Atlantic Ocean gets a few centimeters wider every year.',
  'Mount Everest is still growing — by around 4 millimeters a year.',
  'Antarctica is the largest desert on Earth.',
  'Much of the water you drink is older than the Sun.',
  'Bananas are very slightly radioactive, thanks to their potassium.',
  'A typical fluffy cumulus cloud weighs around 500 tons.',
  'Hawaii drifts several centimeters closer to Japan every year.',
  'Scaled down, the Earth would be smoother than a billiard ball.',
  'Lake Baikal in Siberia holds about a fifth of all the unfrozen fresh surface water on Earth.',
  'The Sahara was green savannah with lakes just a few thousand years ago.',
  'Moonbows exist — rainbows made by moonlight instead of sunlight.',
  'The ocean’s surface isn’t level: variations in gravity make sea level lumpy by many meters.',
  'The smell of rain has a name — petrichor — and much of it comes from a compound made by soil bacteria.',
  'Hot and cold water sound different when poured — you can hear the temperature.',
  'Bamboo can grow close to a meter in a single day.',
  'Young sunflowers track the Sun across the sky; mature ones settle facing east.',
  'Genetically, mushrooms are closer to animals than to plants.',
  'Trees share water and nutrients with each other through underground fungal networks.',
  // ── History & everything else ───────────────────────────────────────
  'Honey found in ancient Egyptian tombs, thousands of years old, was still edible.',
  'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.',
  'Oxford University is older than the Aztec Empire.',
  'Woolly mammoths were still alive on a remote Arctic island while the Egyptian pyramids were being built.',
  'Nintendo was founded in 1889 — it made playing cards.',
  'The fax machine was patented decades before the telephone.',
  'The national animal of Scotland is the unicorn.',
  'Botanically, a banana is a berry — and a strawberry is not.',
  'Humans share roughly half their DNA with bananas.',
  'There are more possible games of chess than atoms in the observable universe.',
  'The Eiffel Tower grows about 15 centimeters taller in summer as its iron expands.',
  'The shortest war in recorded history, between Britain and Zanzibar in 1896, lasted under 45 minutes.',
  'Peanuts aren’t nuts — they’re legumes, like peas.',
  'A pineapple takes the better part of two years to grow.',
  'Before the 17th century, most cultivated carrots were purple.',
  'The dot over a lowercase i or j is called a tittle.',
  'A “jiffy” is a real unit: in physics, the time light takes to travel one centimeter.',
]
