import 'server-only'

// lib/places.ts
//
// Restaurant card data for the /demo/mco canvas, with two backends:
//
// 1. DataForSEO-cached JSON (default; data/mco_live_ratings.json)
//    Pre-resolved Google Maps ratings + review counts for the airport's
//    dining concessions, matched against the authoritative flymco directory.
//    Generated by scripts/_mco_dfs_seed.ts. Cost: ~$0.002 per refresh.
//    Real ratings, real maps_url — no per-render API calls, no key needed.
//
// 2. Google Places API (New) — if GOOGLE_PLACES_API_KEY is set, this path
//    is preserved for callers that pass explicit place_ids (e.g., a future
//    UI that resolves a specific Google place_id from the assistant turn).
//    Basic SKU ($5/1K); Google's TOS only allows caching the place_id, so
//    each call hits the API live.
//
// Fallback when neither is available: an empty list (the card then says
// "no dining matches available") rather than fake ratings — synthetic
// numbers next to a "tap for Google" link mislead the user when the live
// page disagrees.

const PLACES_API = 'https://places.googleapis.com/v1/places/'
// "Basic SKU" field mask — these don't trigger the more expensive
// Pro/Enterprise SKUs. Verify against
// https://developers.google.com/maps/documentation/places/web-service/usage-and-billing
const FIELD_MASK = [
  'displayName',
  'rating',
  'userRatingCount',
  'priceLevel',
  'currentOpeningHours.openNow',
  'formattedAddress',
  'googleMapsUri',
  'primaryType',
].join(',')

export interface PlaceCard {
  place_id: string
  name: string
  rating: number | null
  user_ratings_total: number | null
  price_level: number | null         // 1..4 (PRICE_LEVEL_INEXPENSIVE → PRICE_LEVEL_VERY_EXPENSIVE)
  opening_hours_now: 'open' | 'closed' | 'unknown'
  formatted_address: string
  maps_url: string
  primary_type: string | null         // e.g. "cafe", "restaurant"
  cuisine_icon: string                // emoji glyph derived from name + primary_type
  logo_url: string | null             // brand logo URL — null until a curation pass populates real assets per chain
  is_mock: boolean                    // true when graceful-fallback data
}

// Map a place's name + primary_type to a cuisine emoji. Used as a visual
// classifier on the right-pane card so the list reads richer than a wall of
// text. Brand-name matches take priority (Chick-fil-A as 🐔, Shake Shack as
// 🍔, Wine Bar George as 🍷) because the primary_type from DFS is often the
// generic "Restaurant" for distinctive concepts. Falls through to a
// primary_type lookup, then a generic 🍽️.
export function cuisineIcon(name: string, primaryType: string | null): string {
  const n = (name || '').toLowerCase()
  const t = (primaryType || '').toLowerCase()
  // Name-specific (highest priority — handles brand identity vs. category)
  if (/\bchick-?fil-?a\b/.test(n)) return '🐔'
  if (/\bwine\b/.test(n)) return '🍷'
  if (/cask & larder/.test(n)) return '🍷'
  if (/gastrohub|gastropub/.test(n)) return '🍻'
  if (/\b(burger|shake shack)\b/.test(n)) return '🍔'
  if (/sbarro|desano|pizza/.test(n)) return '🍕'
  if (/le grand comptoir/.test(n)) return '🥐'
  if (/diner|sunshine/.test(n)) return '🥞'
  if (/macaroni|italian (kitchen|restaurant)/.test(n)) return '🍝'
  if (/panda|asian/.test(n)) return '🥡'
  if (/moe|chipotle|taco|on the border/.test(n)) return '🌮'
  if (/outback|steak/.test(n)) return '🥩'
  if (/bahama|caribbean/.test(n)) return '🌴'
  if (/mcdonald/.test(n)) return '🍔'
  if (/starbucks|coffee|espresso|cafe/.test(n)) return '☕'
  // primary_type fallback
  if (/pizza/.test(t)) return '🍕'
  if (/mexican|tacos/.test(t)) return '🌮'
  if (/chinese|asian/.test(t)) return '🥡'
  if (/italian/.test(t)) return '🍝'
  if (/caribbean/.test(t)) return '🌴'
  if (/steak/.test(t)) return '🥩'
  if (/diner/.test(t)) return '🥞'
  if (/salad/.test(t)) return '🥗'
  if (/fast.?food/.test(t)) return '🍔'
  if (/american/.test(t)) return '🍳'
  if (/cafe|coffee/.test(t)) return '☕'
  return '🍽️'
}

// Pre-resolved live rating data, generated by scripts/_mco_dfs_seed.ts.
// Each entry has a real Google Maps rating + review_count + maps_url.
// We load it once at module init so per-request reads are zero-cost.
//
// Shape on disk: { entries: [ { place_id, name, rating, review_count,
//   formatted_address, maps_url, primary_type, opening_hours_now,
//   bucket: "terminal_a_airside" | …, location: "Terminal - A & B" } ] }
import { readFileSync, existsSync } from 'fs'
import path from 'path'

interface LiveRatingEntry {
  place_id: string
  name: string
  matched_dfs_name?: string
  rating: number | null
  review_count: number | null
  formatted_address: string
  maps_url: string
  primary_type: string | null
  opening_hours_now: 'open' | 'closed' | 'unknown'
  bucket: string
  location: string
}

let LIVE_RATINGS: { entries: LiveRatingEntry[] } | null = null
function getLiveRatings(): { entries: LiveRatingEntry[] } {
  if (LIVE_RATINGS) return LIVE_RATINGS
  const p = path.join(process.cwd(), 'data', 'mco_live_ratings.json')
  if (!existsSync(p)) {
    LIVE_RATINGS = { entries: [] }
    return LIVE_RATINGS
  }
  try {
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw)
    LIVE_RATINGS = { entries: Array.isArray(parsed.entries) ? parsed.entries : [] }
  } catch {
    LIVE_RATINGS = { entries: [] }
  }
  return LIVE_RATINGS
}

// Resolve a context label to live-rating cards. Returns empty array if the
// dataset hasn't been seeded yet — the caller renders "no dining matches" in
// that case rather than synthetic ratings.
export function livePlacesForContext(context: string | undefined): PlaceCard[] {
  const ratings = getLiveRatings()
  if (ratings.entries.length === 0) return []
  // Map context → buckets we accept. terminal_a_airside / terminal_b_airside
  // both fall under the flymco "Terminal - A & B" group (the directory doesn't
  // distinguish A vs B on the airside side); show both when either is asked.
  const target = context || 'terminal_a_airside'
  const accept = new Set<string>()
  if (target === 'terminal_a_airside' || target === 'terminal_b_airside') {
    accept.add('terminal_a_airside')
    accept.add('terminal_b_airside')
  } else if (target === 'terminal_c_airside') {
    accept.add('terminal_c_airside')
  } else if (target === 'landside_main_terminal') {
    accept.add('landside_main_terminal')
    accept.add('terminal_a_airside') // fall back to airside if no landside matches
    accept.add('terminal_b_airside')
  } else {
    accept.add(target)
  }

  const filtered = ratings.entries.filter(e => accept.has(e.bucket))
  if (filtered.length === 0) return []
  // Highest-rated first, capped at 8 (Google Places fan-out concurrency limit
  // + a reasonable card-list density)
  const sorted = filtered.slice().sort((a, b) => (b.rating ?? -1) - (a.rating ?? -1)).slice(0, 8)
  return sorted.map(e => ({
    place_id: e.place_id,
    name: e.name,
    rating: e.rating,
    user_ratings_total: e.review_count,
    price_level: null,                   // DFS maps_search doesn't include price level
    opening_hours_now: e.opening_hours_now,
    formatted_address: e.formatted_address,
    maps_url: e.maps_url,
    primary_type: e.primary_type,
    cuisine_icon: cuisineIcon(e.name, e.primary_type),
    logo_url: null,
    is_mock: false,
  }))
}

// Google's PriceLevel enum is a string in the New API. Convert to 1..4.
function priceStringToInt(p: string | undefined | null): number | null {
  switch (p) {
    case 'PRICE_LEVEL_FREE': return 0
    case 'PRICE_LEVEL_INEXPENSIVE': return 1
    case 'PRICE_LEVEL_MODERATE': return 2
    case 'PRICE_LEVEL_EXPENSIVE': return 3
    case 'PRICE_LEVEL_VERY_EXPENSIVE': return 4
    default: return null
  }
}

async function fetchOne(placeId: string, apiKey: string): Promise<PlaceCard | null> {
  try {
    const res = await fetch(PLACES_API + encodeURIComponent(placeId), {
      headers: {
        'X-Goog-Api-Key': apiKey,
        'X-Goog-FieldMask': FIELD_MASK,
      },
      signal: AbortSignal.timeout(5000),
    })
    if (!res.ok) return null
    const j: any = await res.json()
    return {
      place_id: placeId,
      name: j?.displayName?.text || '(unknown)',
      rating: typeof j?.rating === 'number' ? j.rating : null,
      user_ratings_total: typeof j?.userRatingCount === 'number' ? j.userRatingCount : null,
      price_level: priceStringToInt(j?.priceLevel),
      opening_hours_now: typeof j?.currentOpeningHours?.openNow === 'boolean'
        ? (j.currentOpeningHours.openNow ? 'open' : 'closed')
        : 'unknown',
      formatted_address: j?.formattedAddress || '',
      maps_url: j?.googleMapsUri || ('https://www.google.com/maps/place/?q=place_id:' + placeId),
      primary_type: typeof j?.primaryType === 'string' ? j.primaryType : null,
      cuisine_icon: cuisineIcon(j?.displayName?.text || '', typeof j?.primaryType === 'string' ? j.primaryType : null),
      logo_url: null,
      is_mock: false,
    }
  } catch {
    return null
  }
}

/**
 * Resolve a list of place_ids — OR a context label — to PlaceCard rows.
 *
 * Default path: serve from the DataForSEO-seeded JSON (data/mco_live_ratings.json),
 * scoped by `fallbackContext` (e.g. "terminal_a_airside"). Real Google ratings,
 * no per-request cost.
 *
 * GOOGLE_PLACES_API_KEY path (only when explicit place_ids are supplied):
 * fans out direct Google Places API calls for each id. Used when a future
 * UI surface wants to look up a specific place by its Google place_id.
 *
 * If neither path has data, return [] — the card surfaces "no matches" rather
 * than synthetic ratings (which mislead users when they tap through and see
 * different numbers on the real Google page).
 */
export async function fetchPlaceCards(
  placeIds: string[],
  options?: { fallbackContext?: string; concurrency?: number }
): Promise<PlaceCard[]> {
  // Context lookup (no explicit place_ids): serve from the live-rating JSON.
  if (placeIds.length === 0) return livePlacesForContext(options?.fallbackContext)

  // Explicit place_ids supplied: prefer Google Places API if a key is set.
  const apiKey = process.env.GOOGLE_PLACES_API_KEY || ''
  if (!apiKey) {
    // No key + explicit ids → still try the live-rating JSON; many of our
    // entries have a synthesizable place_id from the DFS match. Otherwise
    // empty list (the card renders "no dining matches").
    const live = livePlacesForContext(options?.fallbackContext)
    const byId = new Map(live.map(c => [c.place_id, c]))
    return placeIds.map(pid => byId.get(pid)).filter((c): c is PlaceCard => !!c)
  }

  const concurrency = Math.max(1, Math.min(options?.concurrency || 8, 12))
  const results: PlaceCard[] = []
  let i = 0
  async function worker() {
    while (i < placeIds.length) {
      const idx = i++
      const card = await fetchOne(placeIds[idx], apiKey)
      if (card) results.push(card)
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, placeIds.length) }, worker))
  // Preserve original order in the response
  const byId = new Map(results.map((c) => [c.place_id, c]))
  return placeIds.map((pid) => byId.get(pid)).filter((c): c is PlaceCard => !!c)
}
