import 'server-only'

// lib/shops.ts
//
// Shop directory for the /demo/mco canvas's ShopsCard. Mirrors lib/places.ts
// in spirit — pre-resolved entries from a Playwright scrape of
// flymco.com/shops-restaurants-services filtered to Shop entries.
//
// 60 shops total, bucketed:
//   terminal_ab_airside : 47 (Terminals A & B)
//   terminal_c_airside  : 12 (Terminal C)
//   airport_wide        :  1 (7-Eleven)
//
// Source data: data/mco_shops.json, generated by an inline tsx one-liner
// from /tmp/mco_directory.json. Refresh by re-running
// _mco_scrape_directory.mjs and regenerating the JSON.

import { readFileSync, existsSync } from 'fs'
import path from 'path'

export interface ShopCard {
  id: string
  name: string                         // brand only (e.g. "3Sixty Duty Free")
  location_label: string               // "Terminal - A & B" verbatim from flymco
  location_detail: string | null       // "Gates 70-99" / "Palm Court" / null
  bucket: string                       // terminal_ab_airside | terminal_c_airside | airport_wide
  maps_url: string                     // detail URL on flymco.com
  cuisine_icon: string                 // emoji classifier (re-using the same naming as places)
}

interface ShopsFile {
  fetched_at: string
  count: number
  by_bucket: Record<string, number>
  entries: Array<Omit<ShopCard, 'cuisine_icon'>>
}

let CACHE: ShopsFile | null = null
function loadFile(): ShopsFile {
  if (CACHE) return CACHE
  const p = path.join(process.cwd(), 'data', 'mco_shops.json')
  if (!existsSync(p)) {
    CACHE = { fetched_at: '', count: 0, by_bucket: {}, entries: [] }
    return CACHE
  }
  try {
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw) as ShopsFile
    CACHE = parsed
  } catch {
    CACHE = { fetched_at: '', count: 0, by_bucket: {}, entries: [] }
  }
  return CACHE!
}

// Map shop name to a category emoji. Same spirit as cuisineIcon in places.ts.
// Brand-name priority because most flymco names are well-known retailers.
function shopIcon(name: string): string {
  const n = (name || '').toLowerCase()
  // Specific brands first
  if (/duty.?free|3sixty/.test(n)) return '🛍️'
  if (/sunglass|ray.?ban|oakley/.test(n)) return '🕶️'
  if (/inmotion|tech|electronics|sony|brookstone/.test(n)) return '🎧'
  if (/hudson|news|book|magazine/.test(n)) return '📰'
  if (/disney|magic|kingdom/.test(n)) return '🏰'
  if (/universal/.test(n)) return '🎢'
  if (/swarovski|jewelry|jewellery|tiffany|pandora/.test(n)) return '💍'
  if (/spa|massage|xpresspa|be relax/.test(n)) return '💆'
  if (/toy|build.?a.?bear|lego/.test(n)) return '🧸'
  if (/chocolat|godiva|lindt|sweet|candy/.test(n)) return '🍫'
  if (/cosmetic|mac|sephora|beauty|l.?oreal/.test(n)) return '💄'
  if (/wine|spirit|liquor/.test(n)) return '🍷'
  if (/7.?eleven|convenience|essentials/.test(n)) return '🏪'
  if (/golf/.test(n)) return '⛳'
  if (/shoe|aerosole|foot/.test(n)) return '👟'
  if (/apparel|fashion|clothing|kipling|gap|tommy/.test(n)) return '👕'
  if (/florida|orlando|souvenir|gift/.test(n)) return '🎁'
  return '🛍️'
}

// Map a context label (terminal_a_airside / terminal_b_airside / terminal_c_airside /
// landside_main_terminal) to the buckets we accept. We mirror lib/places.ts —
// flymco's directory doesn't distinguish A from B for shops, so both fall
// under terminal_ab_airside. Airport-wide shops (7-Eleven) come along too.
function bucketsForContext(context: string | undefined): Set<string> {
  const target = context || 'terminal_a_airside'
  const set = new Set<string>()
  if (target === 'terminal_a_airside' || target === 'terminal_b_airside') {
    set.add('terminal_ab_airside')
  } else if (target === 'terminal_c_airside') {
    set.add('terminal_c_airside')
  } else if (target === 'landside_main_terminal') {
    // Landside has very few shops in flymco's directory; show A/B as fallback.
    set.add('terminal_ab_airside')
  } else {
    set.add(target)
  }
  // Always include airport-wide (7-Eleven, etc.)
  set.add('airport_wide')
  return set
}

/**
 * Return shop cards scoped to the given context. Empty array means the
 * seed file is missing — caller should render a friendly fallback.
 * Capped at 12 entries; if filtering empties the bucket, falls back to
 * the top-N across all buckets so the card never blanks.
 */
export function shopsForContext(context: string | undefined): ShopCard[] {
  const file = loadFile()
  if (file.entries.length === 0) return []
  const accept = bucketsForContext(context)
  let filtered = file.entries.filter(e => accept.has(e.bucket))
  if (filtered.length === 0) filtered = file.entries.slice(0, 12)
  return filtered.slice(0, 12).map(e => ({
    ...e,
    cuisine_icon: shopIcon(e.name),
  }))
}
