-- sql/191_stratified_sampling_conversion.sql
-- Finish what sql/188 started: move EVERY sampled_* function off hash order and
-- onto the stratified contiguous-block sample.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHY (measured; full rationale in sql/188's header)
--
-- The old sample is the `cap` rows with the smallest hash(id||dataset_id). It is
-- uniformly random and deterministic, but hash order is UNCORRELATED WITH
-- PHYSICAL order, so the 50,000 sampled rows are scattered at random across a
-- ~922MB heap. Cost is therefore decided by buffer-cache residency, not by row
-- count — the same 5,000 rows took 28ms on one dataset and 1,895ms on another
-- purely because of what happened to be cached. Reading 5,000 rows of the same
-- dataset:
--
--     hash order (today)                     2,296ms
--     systematic every-Nth (row_index % N)   full scan + temp spill  <- unusable
--     one contiguous block                     374ms
--     50 stratified contiguous blocks           41ms   <- ~55x
--     200 blocks                               243ms
--
-- And at 1M rows: hash 36.6s vs stratified 4.8s, with stratified staying FLAT as
-- the dataset grows. That flatness is the point — it is the blocker for 1M.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHY ALL AT ONCE
--
-- The hash sample and the block sample SELECT DIFFERENT ROWS. If the bulk-rows
-- route served one and the count RPCs walked the other, the rows the client
-- holds and the numbers the server reports would describe different samples —
-- a silent, unfalsifiable disagreement. sql/188 converted `sample_dataset_rows`
-- alone and said so explicitly; this migration converts the remaining 19 so the
-- product is never mixed.
--
-- ⚠️ THE NUMBERS MOVE ONCE. Every sampled figure — theme counts, chart
-- aggregates, statistics, anything already exported into a deck — is computed
-- over the sample, so changing the sample changes them. Owner accepted this
-- explicitly (2026-08-15) in preference to carrying two sampling paths forever.
-- Cached analytics must be invalidated when the CODE that calls these lands.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- SHAPE OF THE CONVERSION
--
-- New names (`<name>_blocks`), NOT in-place replacement, for deploy-order
-- safety: between `npm run migrate` and the code deploy, production runs the OLD
-- code, which keeps calling the hash functions and keeps working. The switch
-- happens with the deploy, and rollback is a code revert — no second migration.
--
-- In each function ONLY TWO THINGS CHANGE:
--   1. the sample walk (the `page` / `scan` CTE), and
--   2. the cursor payload: `last_hash` + `last_id` -> `last_row_index`.
-- Every aggregate CTE that reads from `page` is carried through byte-identically.
-- 18 of the 19 were mechanically uniform and were generated by a script that
-- asserts on shape (a hand-typed signature is the one failure mode that silently
-- samples the wrong rows); `sampled_filtered_rows` is hand-written below because
-- its walk CTE is named `scan` and it uses the hash as an ordering key.
--
-- Signature change, uniformly:
--   p_after_hash bigint, p_after_id bigint   ->   p_after_row_index bigint
--   + trailing p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50
--
-- ─────────────────────────────────────────────────────────────────────────────
-- ⚠️ A FLAW IN sql/188 THAT THIS FIXES, and does not replicate 19 times.
--
-- sql/188's pager applies the cursor INSIDE the per-block LATERAL:
--
--     WHERE ... AND f.row_index > p_after_row_index
--     ORDER BY f.row_index LIMIT blk.per_block
--
-- so a block is free to hand out a FRESH per_block rows on every page. A block
-- straddling a page boundary therefore contributes up to twice its share, and
-- with cap=50K / page=5K that is ~10 of the 50 blocks over-weighted — exactly
-- the stratification the design is for.
--
-- Here the per-block LIMIT is taken from the BLOCK START and the cursor filters
-- what has already been selected, so the sampled set is
--   S = "the first per_block rows of each block"
-- which is a fixed set independent of how it is paged. Blocks entirely below the
-- cursor are pruned (`blk.hi > p_after_row_index`) so paging stays cheap; the
-- current block re-reads its own prefix, which is bounded by per_block and
-- sequential. sample_dataset_rows_blocks is re-created below with the same fix.
--
-- DETERMINISM is preserved: S is a pure function of (min row_index, max
-- row_index, cap, blocks) — no hashing, no randomness (ARCHITECTURE.md D6).
--
-- All new functions are SECURITY DEFINER over raw tenant rows and therefore
-- carry the sql/190 lockdown block (service_role only).

BEGIN;
CREATE OR REPLACE FUNCTION public.sampled_count_entity_terms_blocks(p_dataset_id uuid, p_terms text[], p_theme_query text, p_text_fields text[], p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.tsv, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.tsv, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  matched AS (
    SELECT t.term, count(*)::bigint AS n
    FROM unnest(p_terms) AS t(term)
    JOIN page
      ON page.tsv @@ websearch_to_tsquery('english', t.term)          -- tsv prefilter (matches count_entity_terms)
     AND (
       p_text_fields IS NULL
       OR to_tsvector('english', COALESCE(
            (SELECT string_agg(page.data ->> fld, ' ') FROM unnest(p_text_fields) AS fld), '')
          ) @@ websearch_to_tsquery('english', t.term)               -- exact recheck: open-ended fields only
     )
     AND (
       p_theme_query IS NULL
       OR page.tsv @@ websearch_to_tsquery('english', p_theme_query)  -- theme keywords stay on the full row
     )
    GROUP BY t.term
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'counts',    COALESCE((SELECT jsonb_agg(jsonb_build_array(term, n)) FROM matched), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_count_entity_terms_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_count_entity_terms_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_count_entity_terms_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_count_field_values_blocks(p_dataset_id uuid, p_field_key text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  g AS (
    SELECT (data ->> p_field_key)::text AS v, count(*)::bigint AS n
    FROM page
    WHERE (p_row_ids IS NULL OR id = ANY(p_row_ids))
      AND data ->> p_field_key IS NOT NULL
      AND data ->> p_field_key != ''
    GROUP BY 1
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'groups',    COALESCE((SELECT jsonb_agg(jsonb_build_array(v, n)) FROM g), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_count_field_values_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_count_field_values_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_count_field_values_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_crosstab_counts_blocks(p_dataset_id uuid, p_row_field text, p_col_field text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  g AS (
    SELECT COALESCE(data ->> p_row_field, '')::text AS r,
           COALESCE(data ->> p_col_field, '')::text AS c,
           count(*)::bigint AS n
    FROM page
    WHERE (p_row_ids IS NULL OR id = ANY(p_row_ids))
      AND data ->> p_row_field IS NOT NULL
      AND data ->> p_row_field != ''
    GROUP BY 1, 2
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'groups',    COALESCE((SELECT jsonb_agg(jsonb_build_array(r, c, n)) FROM g), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_crosstab_counts_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_crosstab_counts_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_crosstab_counts_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_date_series_stats_blocks(p_dataset_id uuid, p_date_field text, p_metric_field text, p_bucket text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  b AS (
    SELECT
      CASE p_bucket
        WHEN 'week'    THEN to_char(date_trunc('week',    (data ->> p_date_field)::date), 'YYYY-MM-DD')
        WHEN 'month'   THEN to_char(date_trunc('month',   (data ->> p_date_field)::date), 'YYYY-MM')
        WHEN 'quarter' THEN to_char(date_trunc('quarter', (data ->> p_date_field)::date), 'YYYY') || '-Q' || extract(quarter from date_trunc('quarter', (data ->> p_date_field)::date))::text
        WHEN 'year'    THEN to_char(date_trunc('year',    (data ->> p_date_field)::date), 'YYYY')
        ELSE to_char((data ->> p_date_field)::date, 'YYYY-MM-DD')
      END AS bkt,
      count(*)::bigint AS n,
      sum(drf_to_numeric(data ->> p_metric_field))
        FILTER (WHERE p_metric_field IS NOT NULL AND p_metric_field != '' AND drf_numeric_ok(data ->> p_metric_field)) AS msum,
      count(*) FILTER (WHERE p_metric_field IS NOT NULL AND p_metric_field != '' AND drf_numeric_ok(data ->> p_metric_field))::bigint AS mn
    FROM page
    WHERE (p_row_ids IS NULL OR id = ANY(p_row_ids))
      AND data ->> p_date_field IS NOT NULL
      AND data ->> p_date_field != ''
      AND (data ->> p_date_field) ~ '^\d{4}-\d{2}-\d{2}'
    GROUP BY 1
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'buckets',   COALESCE((SELECT jsonb_agg(jsonb_build_array(bkt, n, msum, mn)) FROM b), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_date_series_stats_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_date_series_stats_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_date_series_stats_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_filter_options_blocks(p_dataset_id uuid, p_fields jsonb, p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  fld AS (
    SELECT (e ->> 'field') AS field, (e ->> 'type') AS type, ord
    FROM jsonb_array_elements(p_fields) WITH ORDINALITY AS x(e, ord)
  ),
  -- one (field, row) cell with the RAW extracted text value (untrimmed).
  cells AS MATERIALIZED (
    SELECT fl.ord, fl.field, fl.type, (p.data ->> fl.field) AS raw
    FROM fld fl CROSS JOIN page p
  ),
  agg AS (
    SELECT ord, field, type,
      -- non-empty = count_nonempty_rows (sql/161): trim, all-whitespace is blank
      count(*) FILTER (WHERE NULLIF(btrim(raw), '') IS NOT NULL) AS nonempty,
      -- numeric min/max = numeric_field_stats predicate (no trim)
      min(CASE WHEN type = 'numeric' AND raw ~ '^-?[0-9]+\.?[0-9]*$' THEN raw::double precision END) AS num_min,
      max(CASE WHEN type = 'numeric' AND raw ~ '^-?[0-9]+\.?[0-9]*$' THEN raw::double precision END) AS num_max,
      -- date min/max = legacy .order('data->>field') probe: raw lexical, blanks out
      min(CASE WHEN type = 'date' AND raw IS NOT NULL AND raw <> '' THEN raw END) AS date_min,
      max(CASE WHEN type = 'date' AND raw IS NOT NULL AND raw <> '' THEN raw END) AS date_max
    FROM cells
    GROUP BY ord, field, type
  ),
  vc AS (
    -- distinct value counts = count_field_values (raw data->>field, exclude
    -- null/''; NO trim). ONLY for categorical fields — the Filters modal value-
    -- filters categorical/numeric/date; open-ended is never a checkbox list, so
    -- counting its (high-cardinality free-text) distincts was pure waste and the
    -- ~40s-at-1M cost driver. Capped per page at 2000 by frequency; the Node
    -- caller merges across pages and caps the final list at 500.
    SELECT ord, field,
           jsonb_agg(jsonb_build_object('v', raw, 'c', c) ORDER BY rn) FILTER (WHERE rn <= 2000) AS values,
           count(*) AS distinct_n
    FROM (
      SELECT ord, field, raw, count(*) AS c,
             row_number() OVER (PARTITION BY ord ORDER BY count(*) DESC, raw) AS rn
      FROM cells
      WHERE type = 'categorical' AND raw IS NOT NULL AND raw <> ''
      GROUP BY ord, field, raw
    ) g
    GROUP BY ord, field
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'fields', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'ord',        a.ord,
        'nonempty',   a.nonempty,
        'num_min',    a.num_min,
        'num_max',    a.num_max,
        'date_min',   a.date_min,
        'date_max',   a.date_max,
        'values',     COALESCE(vc.values, '[]'::jsonb),
        'distinct_n', COALESCE(vc.distinct_n, 0)
      ) ORDER BY a.ord), '[]'::jsonb)
      FROM agg a LEFT JOIN vc ON vc.ord = a.ord
    ),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_filter_options_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_filter_options_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_filter_options_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_group_numeric_stats_blocks(p_dataset_id uuid, p_group_field text, p_value_field text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  v AS (
    SELECT COALESCE(data ->> p_group_field, '')::text AS g,
           drf_to_numeric(data ->> p_value_field) AS x
    FROM page
    WHERE (p_row_ids IS NULL OR id = ANY(p_row_ids))
      AND data ->> p_group_field IS NOT NULL
      AND data ->> p_group_field != ''
      AND drf_numeric_ok(data ->> p_value_field)
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'vals',      COALESCE((SELECT jsonb_agg(jsonb_build_array(g, x)) FROM v), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_group_numeric_stats_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_group_numeric_stats_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_group_numeric_stats_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_numeric_field_stats_blocks(p_dataset_id uuid, p_field text, p_aliases jsonb, p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  v AS (
    SELECT CASE
      WHEN p_aliases IS NULL THEN
        CASE WHEN p.data ->> p_field ~ '^-?[0-9]+\.?[0-9]*$'
             THEN (p.data ->> p_field)::double precision END
      ELSE
        CASE WHEN (p_aliases ->> (p.data ->> p_field)) ~ '^-?[0-9]+\.?[0-9]*$'
             THEN (p_aliases ->> (p.data ->> p_field))::double precision END
    END AS x
    FROM page p
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'n',         (SELECT count(x) FROM v),
    'sum',       (SELECT sum(x)   FROM v),
    'min',       (SELECT min(x)   FROM v),
    'max',       (SELECT max(x)   FROM v),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_numeric_field_stats_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_numeric_field_stats_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_numeric_field_stats_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_numeric_field_values_blocks(p_dataset_id uuid, p_field_key text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  v AS (
    SELECT drf_to_numeric(data ->> p_field_key) AS x
    FROM page
    WHERE (p_row_ids IS NULL OR id = ANY(p_row_ids))
      AND drf_numeric_ok(data ->> p_field_key)
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'vals',      COALESCE((SELECT jsonb_agg(x) FROM v), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_numeric_field_values_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_numeric_field_values_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_numeric_field_values_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_signal_counts_blocks(p_dataset_id uuid, p_field_keys text[], p_themes jsonb, p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH pats AS MATERIALIZED (
    SELECT t.ord,
           CASE WHEN t.elem ? 'patterns' THEN
             (SELECT string_agg('(?:^|\W)(?:' || pat || ')', '|')
                FROM jsonb_array_elements_text(t.elem -> 'patterns') AS pat
               WHERE btrim(pat) <> '')
           ELSE
             (SELECT string_agg('(?:^|\W)' || regexp_replace(kw, '([.*+?^${}()|[\]\\])', '\\\1', 'g') || '\w*', '|')
                FROM jsonb_array_elements_text(t.elem -> 'keywords') AS kw
               WHERE btrim(kw) <> '')
           END AS pattern
    FROM jsonb_array_elements(p_themes) WITH ORDINALITY AS t(elem, ord)
  ),
  page AS MATERIALIZED (
    SELECT x.id, x.data, x.substantive, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.substantive, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  rec AS (
    -- per-field non-empty + substantive counts, aligned to p_field_keys order
    SELECT COALESCE(jsonb_agg(cnt     ORDER BY ord), '[]'::jsonb) AS records,
           COALESCE(jsonb_agg(cnt_sub ORDER BY ord), '[]'::jsonb) AS records_substantive
    FROM (
      SELECT fk.ord,
             count(*) FILTER (WHERE NULLIF(btrim(p.data ->> fk.fld), '') IS NOT NULL) AS cnt,
             count(*) FILTER (WHERE p.substantive ? fk.fld)                           AS cnt_sub
      FROM unnest(p_field_keys) WITH ORDINALITY AS fk(fld, ord)
      LEFT JOIN page p ON true
      GROUP BY fk.ord
    ) r
  ),
  hits AS MATERIALIZED (
    SELECT p.id, pt.ord,
           (pt.pattern IS NOT NULL AND EXISTS (
              SELECT 1 FROM unnest(p_field_keys) AS fld
              WHERE p.data ->> fld IS NOT NULL AND p.data ->> fld ~* pt.pattern
           )) AS hit,
           (p.substantive ?| p_field_keys) AS sub
    FROM page p CROSS JOIN pats pt
  ),
  theme_counts AS (
    -- per-theme all-match counts AND the substantive twin (hit AND substantive),
    -- both aligned to theme order. The substantive twin is the prevalence-bar
    -- numerator; the all count stays for any non-substantive consumer.
    SELECT COALESCE(jsonb_agg(cnt     ORDER BY ord), '[]'::jsonb) AS theme_counts,
           COALESCE(jsonb_agg(cnt_sub ORDER BY ord), '[]'::jsonb) AS theme_counts_substantive
    FROM (
      SELECT ord,
             count(*) FILTER (WHERE hit)           AS cnt,
             count(*) FILTER (WHERE hit AND sub)   AS cnt_sub
      FROM hits GROUP BY ord
    ) t
  ),
  union_cnt AS (
    SELECT count(*) FILTER (WHERE any_hit)             AS union_count,
           count(*) FILTER (WHERE any_hit AND any_sub) AS union_count_substantive
    FROM (
      SELECT id, bool_or(hit) AS any_hit, bool_or(sub) AS any_sub
      FROM hits GROUP BY id
    ) u
  )
  SELECT jsonb_build_object(
    'n',                        (SELECT count(*) FROM page),
    'records',                  (SELECT records             FROM rec),
    'records_substantive',      (SELECT records_substantive FROM rec),
    'theme_counts',             (SELECT theme_counts             FROM theme_counts),
    'theme_counts_substantive', (SELECT theme_counts_substantive FROM theme_counts),
    'union_count',              (SELECT union_count             FROM union_cnt),
    'union_substantive',        (SELECT union_count_substantive FROM union_cnt),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_signal_counts_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_signal_counts_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_signal_counts_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_taxonomy_axis_crosstab_blocks(p_dataset_id uuid, p_field text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_field_key text DEFAULT NULL::text, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH fld AS (SELECT taxonomy_field_or_primary(p_dataset_id, p_field_key) AS f),
  page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  g AS (
    SELECT ax.key::text AS axv,
           COALESCE(page.data ->> p_field, '')::text AS fv,
           count(*)::bigint AS n
    FROM page, fld,
         jsonb_each(page.data -> '_tx' -> 'f' -> fld.f -> 'a') AS ax(key, subs),
         jsonb_array_elements_text(ax.subs) AS sub
    WHERE (p_row_ids IS NULL OR page.id = ANY(p_row_ids))
    GROUP BY 1, 2
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'groups',    COALESCE((SELECT jsonb_agg(jsonb_build_array(axv, fv, n)) FROM g), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_taxonomy_axis_crosstab_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_taxonomy_axis_crosstab_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_taxonomy_axis_crosstab_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_taxonomy_crosstab_blocks(p_dataset_id uuid, p_axis text, p_field text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_field_key text DEFAULT NULL::text, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH fld AS (SELECT taxonomy_field_or_primary(p_dataset_id, p_field_key) AS f),
  page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  g AS (
    SELECT sub::text AS s,
           COALESCE(page.data ->> p_field, '')::text AS fv,
           count(*)::bigint AS n
    FROM page, fld,
         jsonb_array_elements_text(page.data -> '_tx' -> 'f' -> fld.f -> 'a' -> p_axis) AS sub
    WHERE (p_row_ids IS NULL OR page.id = ANY(p_row_ids))
    GROUP BY 1, 2
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'groups',    COALESCE((SELECT jsonb_agg(jsonb_build_array(s, fv, n)) FROM g), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_taxonomy_crosstab_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_taxonomy_crosstab_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_taxonomy_crosstab_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_taxonomy_date_series_blocks(p_dataset_id uuid, p_axis text, p_date_field text, p_metric_field text, p_bucket text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_field_key text DEFAULT NULL::text, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH fld AS (SELECT taxonomy_field_or_primary(p_dataset_id, p_field_key) AS f),
  page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  b AS (
    SELECT sub::text AS s,
      CASE p_bucket
        WHEN 'week'    THEN to_char(date_trunc('week',    (page.data ->> p_date_field)::date), 'YYYY-MM-DD')
        WHEN 'month'   THEN to_char(date_trunc('month',   (page.data ->> p_date_field)::date), 'YYYY-MM')
        WHEN 'quarter' THEN to_char(date_trunc('quarter', (page.data ->> p_date_field)::date), 'YYYY') || '-Q' || extract(quarter from date_trunc('quarter', (page.data ->> p_date_field)::date))::text
        WHEN 'year'    THEN to_char(date_trunc('year',    (page.data ->> p_date_field)::date), 'YYYY')
        ELSE to_char((page.data ->> p_date_field)::date, 'YYYY-MM-DD')
      END AS bkt,
      count(*)::bigint AS n,
      sum((page.data ->> p_metric_field)::double precision)
        FILTER (WHERE p_metric_field IS NOT NULL AND p_metric_field != '' AND page.data ->> p_metric_field ~ '^-?[0-9]+\.?[0-9]*$') AS msum,
      count(*) FILTER (WHERE p_metric_field IS NOT NULL AND p_metric_field != '' AND page.data ->> p_metric_field ~ '^-?[0-9]+\.?[0-9]*$')::bigint AS mn
    FROM page, fld,
         jsonb_array_elements_text(page.data -> '_tx' -> 'f' -> fld.f -> 'a' -> p_axis) AS sub
    WHERE (p_row_ids IS NULL OR page.id = ANY(p_row_ids))
      AND page.data ->> p_date_field IS NOT NULL
      AND (page.data ->> p_date_field) ~ '^\d{4}-\d{2}-\d{2}'
    GROUP BY 1, 2
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'buckets',   COALESCE((SELECT jsonb_agg(jsonb_build_array(s, bkt, n, msum, mn)) FROM b), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_taxonomy_date_series_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_taxonomy_date_series_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_taxonomy_date_series_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_taxonomy_group_stats_blocks(p_dataset_id uuid, p_axis text, p_value_field text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_field_key text DEFAULT NULL::text, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH fld AS (SELECT taxonomy_field_or_primary(p_dataset_id, p_field_key) AS f),
  page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  v AS (
    SELECT sub::text AS g,
           (page.data ->> p_value_field)::double precision AS x
    FROM page, fld,
         jsonb_array_elements_text(page.data -> '_tx' -> 'f' -> fld.f -> 'a' -> p_axis) AS sub
    WHERE (p_row_ids IS NULL OR page.id = ANY(p_row_ids))
      AND page.data ->> p_value_field IS NOT NULL
      AND page.data ->> p_value_field ~ '^-?[0-9]+\.?[0-9]*$'
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'vals',      COALESCE((SELECT jsonb_agg(jsonb_build_array(g, x)) FROM v), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_taxonomy_group_stats_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_taxonomy_group_stats_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_taxonomy_group_stats_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_taxonomy_sub_counts_blocks(p_dataset_id uuid, p_axis text, p_after_row_index bigint, p_limit integer, p_row_ids bigint[] DEFAULT NULL::bigint[], p_field_key text DEFAULT NULL::text, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH fld AS (SELECT taxonomy_field_or_primary(p_dataset_id, p_field_key) AS f),
  page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  g AS (
    SELECT sub::text AS v, count(*)::bigint AS n
    FROM page, fld,
         jsonb_array_elements_text(page.data -> '_tx' -> 'f' -> fld.f -> 'a' -> p_axis) AS sub
    WHERE (p_row_ids IS NULL OR page.id = ANY(p_row_ids))
    GROUP BY sub
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'groups',    COALESCE((SELECT jsonb_agg(jsonb_build_array(v, n)) FROM g), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_taxonomy_sub_counts_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_taxonomy_sub_counts_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_taxonomy_sub_counts_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_theme_cooccurrence_page_blocks(p_dataset_id uuid, p_field_keys text[], p_themes jsonb, p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  tp AS (
    SELECT (theme->>'id') AS tid,
           '\m(' || (SELECT string_agg(kw, '|') FROM jsonb_array_elements_text(theme->'keywords') AS kw WHERE kw <> '') || ')' AS pat
    FROM jsonb_array_elements(p_themes) AS theme
    WHERE jsonb_array_length(theme->'keywords') > 0
  ),
  rc AS (
    SELECT page.id, string_agg(coalesce(page.data ->> k, ''), ' ') AS combined
    FROM page, unnest(p_field_keys) AS k
    GROUP BY page.id
  ),
  rt AS (
    SELECT rc.id, array_agg(tp.tid) AS tids
    FROM rc JOIN tp ON rc.combined ~* tp.pat
    GROUP BY rc.id HAVING count(*) >= 2
  ),
  pc AS (
    SELECT a AS ta, b AS tb, count(*)::bigint AS n
    FROM rt, LATERAL unnest(tids) AS a, LATERAL unnest(tids) AS b
    WHERE a <> b GROUP BY a, b
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'pairs',     COALESCE((SELECT jsonb_agg(jsonb_build_array(ta, tb, n)) FROM pc), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_theme_cooccurrence_page_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_theme_cooccurrence_page_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_theme_cooccurrence_page_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_theme_dimension_page_blocks(p_dataset_id uuid, p_field_keys text[], p_themes jsonb, p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  fld AS (SELECT taxonomy_primary_field(p_dataset_id) AS f),
  tp AS (
    SELECT (theme->>'id') AS tid,
           '\m(' || (SELECT string_agg(kw, '|') FROM jsonb_array_elements_text(theme->'keywords') AS kw WHERE kw <> '') || ')' AS pat
    FROM jsonb_array_elements(p_themes) AS theme
    WHERE jsonb_array_length(theme->'keywords') > 0
  ),
  matched AS (   -- (theme, row) where the row's text matches the theme
    SELECT DISTINCT tp.tid, page.id, page.data
    FROM page, tp, unnest(p_field_keys) AS fk(key)
    WHERE page.data ->> fk.key IS NOT NULL
      AND page.data ->> fk.key != ''
      AND page.data ->> fk.key ~* tp.pat
  ),
  dims AS (
    SELECT m.tid, ax.key::text AS axis, sb::text AS sub, count(*)::bigint AS cnt
    FROM matched m, fld,
         jsonb_each(m.data -> '_tx' -> 'f' -> fld.f -> 'a') AS ax(key, subs),
         jsonb_array_elements_text(ax.subs) AS sb
    GROUP BY m.tid, ax.key, sb
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'dims',      COALESCE((SELECT jsonb_agg(jsonb_build_array(tid, axis, sub, cnt)) FROM dims), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_theme_dimension_page_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_theme_dimension_page_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_theme_dimension_page_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_theme_extras_page_blocks(p_dataset_id uuid, p_field_keys text[], p_themes jsonb, p_after_row_index bigint, p_limit integer, p_want_pairs boolean DEFAULT true, p_want_dims boolean DEFAULT true, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  tp AS (
    SELECT (theme->>'id') AS tid,
           '\m(' || (SELECT string_agg(kw, '|') FROM jsonb_array_elements_text(theme->'keywords') AS kw WHERE kw <> '') || ')' AS pat
    FROM jsonb_array_elements(p_themes) AS theme
    WHERE jsonb_array_length(theme->'keywords') > 0
  ),
  -- ── co-occurrence half: sql/173 semantics (fields concatenated) ──────────
  rc AS (
    SELECT page.id, string_agg(coalesce(page.data ->> k, ''), ' ') AS combined
    FROM page, unnest(p_field_keys) AS k
    WHERE p_want_pairs
    GROUP BY page.id
  ),
  rt AS (
    SELECT rc.id, array_agg(tp.tid) AS tids
    FROM rc JOIN tp ON rc.combined ~* tp.pat
    GROUP BY rc.id HAVING count(*) >= 2
  ),
  pc AS (
    SELECT a AS ta, b AS tb, count(*)::bigint AS n
    FROM rt, LATERAL unnest(tids) AS a, LATERAL unnest(tids) AS b
    WHERE a <> b GROUP BY a, b
  ),
  -- ── dimensions half: sql/173 semantics (per-field match) ────────────────
  fld AS (SELECT taxonomy_primary_field(p_dataset_id) AS f),
  matched AS (
    SELECT DISTINCT tp.tid, page.id, page.data
    FROM page, tp, unnest(p_field_keys) AS fk(key)
    WHERE p_want_dims
      AND page.data ->> fk.key IS NOT NULL
      AND page.data ->> fk.key != ''
      AND page.data ->> fk.key ~* tp.pat
  ),
  dims AS (
    SELECT m.tid, ax.key::text AS axis, sb::text AS sub, count(*)::bigint AS cnt
    FROM matched m, fld,
         jsonb_each(m.data -> '_tx' -> 'f' -> fld.f -> 'a') AS ax(key, subs),
         jsonb_array_elements_text(ax.subs) AS sb
    GROUP BY m.tid, ax.key, sb
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'pairs',     COALESCE((SELECT jsonb_agg(jsonb_build_array(ta, tb, n)) FROM pc), '[]'::jsonb),
    'dims',      COALESCE((SELECT jsonb_agg(jsonb_build_array(tid, axis, sub, cnt)) FROM dims), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_theme_extras_page_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_theme_extras_page_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_theme_extras_page_blocks TO service_role;


CREATE OR REPLACE FUNCTION public.sampled_theme_topical_page_blocks(p_dataset_id uuid, p_field_keys text[], p_themes jsonb, p_extra_excludes text[], p_after_row_index bigint, p_limit integer, p_cap integer DEFAULT 50000, p_blocks integer DEFAULT 50)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    -- Per-block LIMIT from the BLOCK START, cursor applied outside. Filtering
    -- inside the LATERAL instead (sql/188) lets a block straddling a page
    -- boundary hand out a fresh per_block rows on every page.
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  ),
  tp AS (
    SELECT (theme->>'id') AS tid,
           '\m(' || (SELECT string_agg(kw, '|') FROM jsonb_array_elements_text(theme->'keywords') AS kw WHERE kw <> '') || ')' AS pat
    FROM jsonb_array_elements(p_themes) AS theme
    WHERE jsonb_array_length(theme->'keywords') > 0
  ),
  row_text AS (
    SELECT page.id, string_agg(lower(coalesce(page.data ->> k, '')), ' ') AS combined
    FROM page, unnest(p_field_keys) AS k
    GROUP BY page.id
  ),
  tokens AS (
    SELECT rt.id, tk.word, tk.pos
    FROM row_text rt,
         LATERAL unnest(regexp_split_to_array(rt.combined, '[^a-z0-9'']+')) WITH ORDINALITY AS tk(word, pos)
    WHERE tk.word IS NOT NULL AND tk.word != ''
  ),
  kw_positions AS (   -- token positions where each theme's keywords hit
    SELECT tp.tid, tp.pat, t.id, t.pos
    FROM tokens t JOIN tp ON t.word ~* tp.pat
  ),
  window_words AS (   -- ±2 window per (theme, keyword-hit), excluding the hit position
    SELECT kp.tid, kp.pat, t.word
    FROM tokens t
    JOIN kw_positions kp ON t.id = kp.id
    WHERE t.pos BETWEEN kp.pos - 2 AND kp.pos + 2 AND t.pos <> kp.pos
  ),
  filtered AS (
    SELECT tid, word, count(*)::bigint AS cnt
    FROM window_words ww
    WHERE length(word) >= 3
      AND word !~ '^[0-9]+$'
      AND word !~* ww.pat                          -- exclude that theme's own keyword stems
      AND NOT (word = ANY(p_extra_excludes))
      AND NOT (word = ANY(topical_stopwords()))
    GROUP BY tid, word
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM page),
    'words',     COALESCE((SELECT jsonb_agg(jsonb_build_array(tid, word, cnt)) FROM filtered), '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  );
$$;

REVOKE ALL ON FUNCTION public.sampled_theme_topical_page_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_theme_topical_page_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_theme_topical_page_blocks TO service_role;

-- ── The one non-uniform function, hand-written ──────────────────────────────
-- sampled_filtered_rows names its walk CTE `scan` (not `page`) and uses the hash
-- as an ORDERING key in two more places: which matched rows survive
-- p_match_limit, and the order they come back in. Under block sampling the
-- equivalent order is row_index — same intent (a stable, sample-order cut),
-- different key.

CREATE OR REPLACE FUNCTION public.sampled_filtered_rows_blocks(
  p_dataset_id      uuid,
  p_filters         jsonb,
  p_after_row_index bigint,
  p_scan_limit      integer,
  p_match_limit     integer,
  p_cap             integer DEFAULT 50000,
  p_blocks          integer DEFAULT 50
)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  WITH scan AS MATERIALIZED (
    SELECT x.id, x.data, x.row_index
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.data, f.row_index
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_scan_limit
  ), matched AS MATERIALIZED (
    SELECT s.id, s.data, s.row_index
    FROM scan s
    WHERE public.ana_row_matches_filters(s.data, p_filters)
  )
  SELECT jsonb_build_object(
    'n_scanned', (SELECT count(*) FROM scan),
    'n_matched', (SELECT count(*) FROM matched),
    'rows', COALESCE(
      (SELECT jsonb_agg(m.data ORDER BY m.row_index)
       FROM (SELECT id, data, row_index FROM matched ORDER BY row_index LIMIT p_match_limit) m),
      '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM scan)
  );
$$;

COMMENT ON FUNCTION public.sampled_filtered_rows_blocks(uuid, jsonb, bigint, integer, integer, integer, integer) IS
  'Stratified-block twin of sampled_filtered_rows (sql/191). Same filter semantics (ana_row_matches_filters) and the same {n_scanned, n_matched, rows} contract; the hash ordering key is replaced by row_index, which is the block sample''s natural order.';

REVOKE ALL ON FUNCTION public.sampled_filtered_rows_blocks FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sampled_filtered_rows_blocks FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sampled_filtered_rows_blocks TO service_role;

-- ── Re-create sql/188's bulk sampler with the page-boundary fix ─────────────
-- Same contract and same reserved-key/p_drop_keys behaviour as sql/188; the only
-- change is that the per-block LIMIT is taken from the block start and the
-- cursor is applied outside the LATERAL, so a block straddling a page boundary
-- can no longer hand out a second full per_block allocation. Without this the
-- bulk rows and the count RPCs would drift apart at page boundaries — the exact
-- mixing hazard the all-at-once conversion exists to prevent.

CREATE OR REPLACE FUNCTION public.sample_dataset_rows_blocks(
  p_dataset_id       uuid,
  p_after_row_index  bigint,
  p_limit            int,
  p_cap              int DEFAULT 50000,
  p_blocks           int DEFAULT 50,
  p_drop_keys        text[] DEFAULT '{}'
)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH page AS MATERIALIZED (
    SELECT x.id, x.row_index, x.data
    FROM (
      SELECT b.lo, b.hi,
             (p_cap::numeric / greatest(count(*) OVER (), 1))::int + 1 AS per_block
      FROM dataset_sample_blocks(p_dataset_id, p_cap, p_blocks) b
    ) blk, LATERAL (
      SELECT f.id, f.row_index,
             ((f.data - '_tx' - '_txv' - '_sub') - COALESCE(p_drop_keys, '{}'::text[])) AS data
      FROM dataset_rows_flat f
      WHERE f.dataset_id = p_dataset_id
        AND f.row_index >= blk.lo AND f.row_index < blk.hi
      ORDER BY f.row_index
      LIMIT blk.per_block
    ) x
    WHERE blk.hi > p_after_row_index AND x.row_index > p_after_row_index
    ORDER BY x.row_index
    LIMIT p_limit
  )
  SELECT jsonb_build_object(
    'rows', COALESCE(
      jsonb_agg(jsonb_build_object('id', id, 'row_index', row_index, 'data', data) ORDER BY row_index),
      '[]'::jsonb),
    'last_row_index', (SELECT max(row_index) FROM page)
  ) FROM page;
$$;

COMMENT ON FUNCTION public.sample_dataset_rows_blocks(uuid, bigint, int, int, int, text[]) IS
  'Bulk-row sampler over the sql/188 stratified block set. sql/191 moved the per-block LIMIT to the BLOCK START and applies the cursor outside the LATERAL: previously a block straddling a page boundary handed out a fresh per_block rows on every page, over-weighting roughly one block per page. The sampled set is now "the first per_block rows of each block", independent of how it is paged.';

REVOKE ALL ON FUNCTION public.sample_dataset_rows_blocks(uuid, bigint, int, int, int, text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sample_dataset_rows_blocks(uuid, bigint, int, int, int, text[]) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sample_dataset_rows_blocks(uuid, bigint, int, int, int, text[]) TO service_role;

COMMIT;

-- Verify (all 20 blocks twins present, none anon-executable):
--   SELECT p.oid::regprocedure, has_function_privilege('anon', p.oid, 'EXECUTE')
--     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--    WHERE n.nspname = 'public' AND p.proname LIKE '%\_blocks' ORDER BY 1;
